server:
  port: 9876

  servlet:
    context-path: /demicar
spring:
  application:
    name: demicar
  profiles:
    active: dev # El perfil predeterminado es 'dev'

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://demicar.matias:5432/demicar_dev
    username: postgres
    password: mla
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://demicar.matias:5432/demicar_test
    username: postgres
    password: mla
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://demicar.matias:5432/demicar_prod
    username: postgres
    password: mla
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
